### ISSUE TITLE
Uncaught (in promise) Error: (SystemJS) XHR error (404 Not Found) loading http://localhost:9000/dist/deepmerge.js

### ISSUE THREAD

**Issue by RonnieBarnard** [miguelzakharia/aurelia-google-analytics#26] opened 2017-06-26 23:59 UTC
Uncaught (in promise) Error: (SystemJS) XHR error (404 Not Found) loading http://localhost:9000/dist/deepmerge.js

**Comment by RonnieBarnard** [comment] 2017-06-27 00:00
I followed the installation notes:

1. jspm install ...
2. Modified main.ts
3. gulp watch
4. http://localhost:9000

and get this error.

I commented the plugin in main, and the site loads, uncomment and it fails..

**Comment by miguelzakharia** [comment] 2017-07-03 21:36
I haven't used JSPM for a long time. From what I recall, dependencies need to be added to the `jspm` section in `package.json`. If you already did that, then I'll download the [Aurelia Skeleton](https://github.com/aurelia/skeleton-navigation/tree/master/skeleton-esnext) project and try to reproduce the issue.

**Comment by RonnieBarnard** [comment] 2017-07-10 17:17
I have not added it into the Package file, it added one in automatically under Jspm, dependencies:

"aurelia-google-analytics": "github:miguelzakharia/aurelia-google-analytics@^2.3.0",

What would the dependency setup look like to go into the package.json file?

EDIT:
  "dependencies": {
    "buffer-shims": "^1.0.0",
    "deepmerge": "^1.4.4",
    "graceful-fs": "^4.1.11",
    "natives": "^1.1.0"
  }

This is a section that was added as well. I see deepmerge is specified

**Comment by RonnieBarnard** [comment] 2017-07-10 17:25
A bit more information:

Uncaught (in promise) Error: (SystemJS) XHR error (404 Not Found) loading http://localhost:9000/dist/deepmerge.js
	Error: XHR error (404 Not Found) loading http://localhost:9000/dist/deepmerge.js
	Error loading http://localhost:9000/dist/deepmerge.js as "deepmerge" from http://localhost:9000/jspm_packages/github/miguelzakharia/aurelia-google-analytics@2.3.0/analytics.js

This is the console error that pops up. I installed deepmerge through npm, but it does not include a file called deepmerge.js

**Comment by zubair1024** [comment] 2017-09-18 18:43
Is this issue resolved? I seem to be facing the same.

P.S. I used npm and edited aurelia.json for the include.

**Comment by miguelzakharia** [comment] 2017-09-18 20:03
No, I have not had time to dig into this. Any help from someone that is familiar with JSPM is appreciated.

**Comment by niemyjski** [comment] 2017-10-06 20:31
I'm also running into this.

**Comment by rockResolve** [comment] 2017-11-03 00:21
I found this too.

The problem is package.json jspm.dependencies lists aurelia-dependency-injection , aurelia-event-aggregator, & aurelia-logging, but is missing deepmerge.

PR created #27 

**Workaround**
Install it overriding the jspm dependencies with:
`jspm install aurelia-google-analytics -o "{ dependencies: { 'aurelia-dependency-injection': 'npm:aurelia-dependency-injection@^1.3.0', 'aurelia-event-aggregator': 'npm:aurelia-event-aggregator@^1.0.1', 'aurelia-logging': 'npm:aurelia-logging@^1.2.0', 'deepmerge': 'npm:deepmerge@^1.3.2' } }"`

**Comment by miguelzakharia** [comment] 2017-11-07 00:11
Fixed by [PR 27](https://github.com/miguelzakharia/aurelia-google-analytics/pull/27).

Thank you, @rockResolve

**Closed as completed by miguelzakharia** 2017-11-07 00:11 UTC
Labels: bug, help wanted
